### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [IFEERnD/v5Pfes#1]
# problem

Can you please change the Plugin home page to point to this repo as I see that the current one does not relate to the plugin at all

**Comment by IFEERnD** [comment]
Thanks for your comment, ihave change our plugin repo to Github link

Vào Th 5, 20 thg 10, 2022 vào lúc 14:11 mazano ***@***.***>
đã viết:

**Comment by rduivenvoorde** [comment]
@NyakudyaA is it ok like this?

**Comment by NyakudyaA** [comment]
@rduivenvoorde They need to upload a new version as the current one still references the old link then I can approve

**Comment by rduivenvoorde** [comment]
@NyakudyaA they renamed the plugin, hopefully @IFEERnD can have a look?

**Comment by IFEERnD** [comment]
@rduivenvoorde Thank you i'll update this

**Comment by IFEERnD** [comment]
@NyakudyaA yes i have been update a new version with new name for 3 week ago but still not have approved. Could you please check again
![image](https://user-images.githubusercontent.com/113353979/206329992-b7d6e776-6d25-425b-8aab-af2a4d8da139.png)

**Comment by NyakudyaA** [comment]
> @NyakudyaA yes i have been update a new version with new name for 3 week ago but still not have approved. Could you please check again ![image](https://user-images.githubusercontent.com/113353979/206329992-b7d6e776-6d25-425b-8aab-af2a4d8da139.png)
The issue is highlighted in the image below
![plugin-dummy](https://user-images.githubusercontent.com/2510900/206510279-63da6338-8a4b-49cc-a1cf-1c92f6aeb37c.png)

**Comment by rduivenvoorde** [comment]
@IFEERnD the crux is that the 'Plugin home page' should either link to a dedicated page giving information about the plugin, OR just to this repo , so people can read the README.
NOw you are linking to a general page of the institution...

**Comment by IFEERnD** [comment]
@rduivenvoorde Thank you, I have been update home page information as you suggest. Please help me check again.

**Comment by IFEERnD** [comment]
@rduivenvoorde @NyakudyaA could you please check again if our plugin have anny missing. thank you!

**Comment by NyakudyaA** [comment]
LGTM

**Comment by IFEERnD** [comment]
thank for your help!

Vào Th 6, 16 thg 12, 2022 vào lúc 14:10 mazano ***@***.***>
đã viết:
